### ISSUE TITLE
Rename devices

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/stream-ioc#1]
@ito-rafael ,

- I have renamed all PVs in this repository according to the new pulsed magnet device names.
- I also fixed the discipline part of the name, replacing 'PM' (pulsed magnets) to 'PU' (power supplies for pulsed magnets).
- I meant to commit to the branch "PR-rename-devices"so that you could have a chance to look at the code before merging it but, at the end, I pushed to master by mistake. sorry!
- Please check if this commit did not break the code.

**Comment by ito-rafael** [comment]
I have just tested the changes here in my lab and seems the code didn't break or anything. Later I'll test together with Pulse Power Supply (EPP) guys just to be sure things are working. But for now, I think it's ok to close this issue.
And don't worry about pushing to master. Since everything seems to be working, it shouldn't have any problem.
